'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const project={title:'古画智能修复',summary:'围绕参考资料、方案比较与人工判断，探索人工智能如何参与古画修复的研究过程。',stage:'已有初版研究软件',owner:'成员资料由团队补充',perspectives:['culture','interaction'],problem:'当 AI 参与古画修复，研究者如何理解建议的依据，并作出自己的判断？',human:'研究人员选择参考资料，比较方案中的差异，结合文化语境判断哪些建议值得进一步讨论。',ai:'探索利用智能方法组织相关资料、形成候选方案与预览，帮助研究人员开展比较。',method:'从具体修复问题出发，整理文化资料与已有参考。\n用软件原型组织资料、方案和预览，观察人在各个环节需要什么支持。\n围绕依据是否充分、方案如何比较、人工判断如何记录，继续完善研究方法。',progress:'已有初版软件作为研究基础。资料的证据组织、方案比较与人工确认机制仍在持续完善。',memberIds:[],outputIds:['software']};
let draft=structuredClone(project),savedDraft=structuredClone(project),editorTab='basics',adminType='project',outputFilter='all',perspectiveIndex=0,previewing=false,toast='';
const perspectives=[
 {id:'generation',title:'生成模型',question:'如何让生成模型更高效、更可控？',body:'关注扩散与流匹配模型的蒸馏、后训练及生成内容评价。算法本身也是研究对象。',work:'disback'},
 {id:'interaction',title:'人机协作',question:'人如何理解、参与并影响智能系统？',body:'关注交互式人机协作，让人的意图、操作与判断进入生成和探索过程。',work:'poempalette'},
 {id:'culture',title:'文化与创作',question:'智能技术如何支持文化的理解、创造与体验？',body:'以古画、诗歌等具体文化内容为对象，探索生成方法与交互体验。',work:'ink-restorer'}
];
const arrow=(href,label)=>`<a class="link-arrow" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const inline=(href,label)=>`<a class="inline-link" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const heading=(title,description='',crumb='')=>`<div class="page-heading">${crumb?`<div class="breadcrumbs"><a href="#/">首页</a><span>/</span>${crumb}</div>`:''}<h1>${title}</h1>${description?`<p>${description}</p>`:''}</div>`;

function perspectivePanel(i){const p=perspectives[i],w=works.find(w=>w.id===p.work);return `<h3>${p.question}</h3><p>${p.body}</p>${inline('#/research/'+w.id,'关联研究：'+w.name)}`;}
function workRows(){return works.map(w=>`<article class="work-row"><div class="work-year">${w.venue} / ${w.year}<span>${w.theme}</span></div><div><h3><a href="#/research/${w.id}">${w.name}</a></h3><p>${w.summary}</p></div>${inline('#/research/'+w.id,'阅读研究')}</article>`).join('');}
function home(){return `<div class="shell">
 <section class="hero" aria-labelledby="home-title"><div class="hero-copy"><p class="hero-kicker">GAN lab / 浙江大学团队</p><h1 id="home-title">AI、人机交互<br>与传统文化<span>。</span></h1><p class="hero-description">研究生成模型与人机协作，探索智能技术<br class="desktop-break">在文化理解、创造与体验中的新可能。</p><div class="hero-actions">${arrow('#/research','了解我们的研究')}<a class="quiet-link" href="#/people">认识团队 ↗</a></div></div><figure class="hero-image"><img src="assets/culture-computation-concept.png" alt="水墨山形与同形采样点云的黑白概念视觉" width="1536" height="1024" fetchpriority="high"></figure><div class="hero-caption"><span>Culture × Computation</span><span>原创概念视觉</span></div></section>
 <section class="research-intro" aria-labelledby="questions-title"><h2 class="section-title" id="questions-title">从生成方法，到人的文化体验。</h2><p class="section-subtitle">研究生成模型本身，也关注人与智能系统怎样共同创作。<br>传统文化为研究带来具体问题，这些主题在不同工作中交汇。</p><div class="perspectives"><div class="perspective-menu" role="tablist" aria-label="研究视角">${perspectives.map((p,i)=>`<button role="tab" id="perspective-tab-${i}" aria-selected="${i===perspectiveIndex}" aria-controls="perspective-panel" tabindex="${i===perspectiveIndex?0:-1}" data-perspective="${i}">${p.title}<span aria-hidden="true">↗</span></button>`).join('')}</div><div class="perspective-panel" id="perspective-panel" role="tabpanel" aria-labelledby="perspective-tab-${perspectiveIndex}">${perspectivePanel(perspectiveIndex)}</div></div></section>
 <section class="featured-section" aria-labelledby="featured-title"><div class="section-topline"><div><h2 class="section-title" id="featured-title">精选研究</h2><p class="section-subtitle">导师参与的算法与交互研究，从不同角度回应人与智能的问题。</p></div>${inline('#/outputs','查看论文')}</div><div class="work-list">${workRows()}</div></section>
 <section class="lab-section" aria-labelledby="lab-title"><div><h2 class="section-title" id="lab-title">关于 GAN lab</h2><p>我们是浙江大学团队，导师为李泽健。关注生成模型、人机协作，以及智能技术与传统文化的交叉研究。</p><div class="resource-names"><span>相关学术资源</span><span>浙江大学国际设计研究院</span><span>浙江大学软件学院 · 浙江大学人工智能学院</span></div>${inline('#/about','了解团队背景')}</div><div class="conversation"><h3>从一个值得研究的问题开始交流。</h3><a href="#/contact?intent=academic">学术交流 <span>研究问题与方法 ↗</span></a><a href="#/contact?intent=culture">文化场景合作 <span>具体对象与人的工作 ↗</span></a><a href="#/contact?intent=join">了解参与方式 <span>研究兴趣与团队工作 ↗</span></a></div></section>
 </div>`;}
function research(){return `<div class="shell">${heading('研究','研究智能生成的方法，理解人的交互与判断，探索文化创作的新可能。','研究')}<section class="page-section"><h2>我们关注的问题</h2><div class="research-questions">${perspectives.map(p=>`<article class="research-question"><h3>${p.title}</h3><div><p class="question">${p.question}</p><p>${p.body}</p>${inline('#/research/'+p.work,'阅读关联研究')}</div></article>`).join('')}</div></section><section class="page-section"><h2>精选研究</h2><p class="section-subtitle">以下为导师参与的公开工作。每项研究连接方法、论文与研究者。</p>${workRows()}</section></div>`;}
function workDetail(w){return `<article class="shell"><div class="page-heading"><div class="breadcrumbs"><a href="#/research">研究</a><span>/</span>${w.name}</div><p class="hero-kicker">${w.theme} / ${w.venue} ${w.year}</p><h1>${w.name}</h1><p>${w.summary}</p><dl class="project-metadata"><div><dt>发表信息</dt><dd>${w.stage}</dd></div><div><dt>导师参与</dt><dd><a href="#/people">李泽健 ↗</a></dd></div></dl></div><div class="project-reading"><nav class="project-toc" aria-label="项目内容"><a href="#work-question" data-section="work-question">研究问题</a><a href="#work-method" data-section="work-method">研究方法</a><a href="#work-paper" data-section="work-paper">论文与研究者</a><a href="#/contact?intent=academic">交流研究 ↗</a></nav><div class="project-body"><section id="work-question"><h2>研究问题</h2><p class="research-statement">${w.question}</p></section><section id="work-method"><h2>如何开展研究</h2><p>${w.method}</p><div class="activity-list"><div class="activity-row"><strong>${w.id==='disback'?'研究者':'人的活动'}</strong><p>${w.human}</p></div><div class="activity-row"><strong>${w.id==='disback'?'算法目标':'AI 的作用'}</strong><p>${w.ai}</p></div></div></section><section id="work-paper"><h2>论文与研究者</h2><div class="paper-citation"><span>${w.venue} · ${w.year}</span><h3>${w.title}</h3><p>李泽健参与的研究 · 完整作者及贡献信息见论文</p><a class="inline-link" href="${w.url}" target="_blank" rel="noopener">阅读原文 ↗</a>${w.code?`<a class="inline-link" href="${w.code}" target="_blank" rel="noopener">项目代码 ↗</a>`:''}</div><div class="related-row"><div><strong>李泽健 · Zejian Li</strong><span>团队导师 / 生成模型与智能设计</span></div>${inline('#/people','认识研究者')}</div><p class="small-note">资料来源：${w.source}。${w.sourceUrl?`<a href="${w.sourceUrl}" target="_blank" rel="noopener">学院成果介绍 ↗</a>`:""} 网站介绍为简要整理，研究细节请阅读原文。</p>${inline('#/contact?intent=academic','交流相关问题')}</section></div></div></article>`;}
function projectDetail(p,isPreview=false){return `<article class="shell">${isPreview?`<div class="preview-ribbon"><span>后台样例草稿预览 · 不属于公开研究列表</span><button data-return-editor>返回编辑</button></div>`:''}<div class="page-heading project-header"><div class="breadcrumbs"><a href="#/research">研究</a><span>/</span><span>${esc(p.title||'未命名研究')}</span></div><h1>${esc(p.title||'未命名研究')}</h1><p>${esc(p.summary)}</p><dl class="project-metadata"><div><dt>研究关联</dt><dd>${p.perspectives.map(id=>esc(perspectives.find(x=>x.id===id)?.title||id)).join(' / ')||'尚未选择'}</dd></div><div><dt>当前阶段</dt><dd>${esc(p.stage)}</dd></div><div><dt>内容类型</dt><dd>研究项目 / 软件原型</dd></div></dl></div><div class="project-reading"><nav class="project-toc" aria-label="项目内容"><a href="#project-question" data-section="project-question">研究问题</a><a href="#project-activity" data-section="project-activity">人和 AI 的角色</a><a href="#project-method" data-section="project-method">方法与阶段</a><a href="#project-related" data-section="project-related">相关内容</a><a href="#/contact?intent=culture">讨论这个问题 ↗</a></nav><div class="project-body"><section id="project-question"><h2>研究问题</h2><p class="research-statement">${esc(p.problem)}</p><p>从一处具体的文化图像问题出发，关注资料与方案的依据，以及研究者如何理解、比较并保留自己的判断。</p></section><section id="project-activity"><h2>人和 AI 分别参与什么</h2><div class="activity-list"><div class="activity-row"><strong>人的活动</strong><p>${esc(p.human)}</p></div><div class="activity-row"><strong>AI 的作用</strong><p>${esc(p.ai)}</p></div><div class="activity-row"><strong>交互问题</strong><p>怎样呈现资料与方案的关系，怎样比较差异，以及人的反馈如何进入下一步？这些问题共同决定智能方法能否支持实际研究。</p></div></div></section><section id="project-method"><h2>如何开展研究</h2><ul class="method-list">${p.method.split('\n').filter(Boolean).map(line=>`<li>${esc(line)}</li>`).join('')}</ul><h2 style="margin-top:30px">当前阶段</h2><p>${esc(p.progress)}</p></section><section id="project-related"><h2>相关成果与团队</h2>${p.outputIds.includes('software')?`<div class="related-row"><div><strong>古画修复初版软件</strong><span>软件原型 / 已有研究基础</span></div><span class="small-note">后台关联样例</span></div>`:'<p>尚未关联成果。可以先了解研究方法，成果由老师后续关联。</p>'}<div class="related-row"><div><strong>相关研究者</strong><span>${esc(p.owner)}</span></div><span class="small-note">参与者待填写</span></div><div class="soft-note">项目持续围绕<strong>文化资料、候选方案与人的判断</strong>展开。有关文化对象、专业工作流程或交互评价的研究问题，可以进一步交流。</div>${inline('#/contact?intent=culture','讨论相关研究问题')}</section></div></div></article>`;}
function outputs(){let shown=outputFilter==='all'||outputFilter==='papers'?works:outputFilter==='tools'?works.filter(w=>w.code):[];return `<div class="shell outputs-layout">${heading('论文与研究资源','导师参与的精选论文，以及可以继续访问的研究资源。','成果')}<div class="chip-group" aria-label="成果类型">${[['all','全部'],['papers','论文'],['tools','代码'],['data','数据与资源']].map(([id,label])=>`<button class="chip" aria-pressed="${id===outputFilter}" data-output-filter="${id}">${label}</button>`).join('')}</div><div class="outputs-body" aria-live="polite">${shown.length?shown.map(w=>`<article class="output-item"><span class="kind">${w.venue}<br>${w.year}</span><div><h2><a href="#/research/${w.id}">${w.title}</a></h2><p>${w.summary}</p><p class="small-note">李泽健参与的研究 · 完整作者见原文</p><div class="paper-actions">${inline('#/research/'+w.id,'研究介绍')}<a class="inline-link" href="${outputFilter==='tools'?w.code:w.url}" target="_blank" rel="noopener">${outputFilter==='tools'?'项目代码':'论文原文'} ↗</a></div></div></article>`).join(''):`<section class="empty-content"><h2>数据与资源链接尚未补充</h2><p>可以从论文或研究代码继续了解工作。</p>${inline('#/research','浏览研究')}</section>`}</div><p class="small-note">更多论文见 <a href="${mentorHome}" target="_blank" rel="noopener">李泽健个人学术主页 ↗</a></p></div>`;}

function people(){return `<div class="shell">${heading('团队','研究生成模型与人机协作，探索人与智能、文化之间的联系。','团队')}<section class="mentor-profile"><div class="mentor-name"><p class="hero-kicker">团队导师</p><h2>李泽健</h2><p>Zejian Li</p><span>浙江大学软件学院<br>平台“百人计划”研究员</span></div><div class="mentor-bio"><p class="lead">关注生成模型与智能设计。</p><p>研究涉及扩散与流匹配模型的蒸馏和后训练、生成内容评价，以及交互式人机协作应用；同时开展人工智能辅助文化遗产保护研究。</p><p>2019 年获浙江大学计算机科学与技术博士学位。现为浙江大学人工智能学院孙凌云教授团队成员。</p><div class="paper-actions"><a class="inline-link" href="${universityHome}" target="_blank" rel="noopener">浙大教师主页 ↗</a><a class="inline-link" href="${mentorHome}" target="_blank" rel="noopener">个人学术主页 ↗</a></div></div></section><section class="page-section"><div class="section-topline"><h2>参与的精选研究</h2>${inline('#/outputs','查看论文')}</div>${workRows()}</section><section class="page-section"><h2>更多成员</h2><p class="section-subtitle">成员的研究兴趣、参与项目与个人介绍由团队陆续补充。</p></section><section class="page-section"><h2>了解参与方式</h2><p class="section-subtitle">对生成模型或人机协同创作感兴趣，可以从具体工作开始了解，再交流研究兴趣与参与方式。</p>${inline('#/contact?intent=join','了解如何联系')}<p class="small-note">招生与实习说明见导师个人主页，具体名额以当年安排为准。</p></section></div>`;}
function about(){return `<div class="shell">${heading('关于 GAN lab','在人工智能、人机交互与传统文化的交叉处，开展面向具体问题的研究。','关于')}<section class="page-section about-grid"><h2>团队与研究</h2><div><p>GAN lab 是浙江大学团队。官网以研究为主线，介绍关注的问题、具体项目、相关成果与研究者。</p><p style="margin-top:16px">团队导师为李泽健。研究生成模型与智能设计，并关注人机协作与文化遗产保护。</p>${inline('#/research','探索研究问题')}</div></section><section class="page-section about-grid"><h2>相关学术资源</h2><div><div class="resource-row">浙江大学国际设计研究院<a href="http://idi.zju.edu.cn/" target="_blank" rel="noopener">访问官网 ↗</a></div><div class="resource-row">浙江大学软件学院<a href="https://www.cst.zju.edu.cn/" target="_blank" rel="noopener">访问官网 ↗</a></div><div class="resource-row">浙江大学人工智能学院<a href="https://ai.zju.edu.cn/" target="_blank" rel="noopener">访问官网 ↗</a></div></div></section><section class="page-section about-grid"><h2>研究动态</h2><div><p>研究动态即将补充。当前可从研究页了解已有工作。</p>${inline('#/research','查看研究')}</div></section><section class="page-section about-grid"><h2>交流与合作</h2><div><p>学术方法、文化场景或研究参与，可以从各自关心的问题开始交流。</p>${inline('#/contact','选择交流主题')}</div></section></div>`;}
const contactIntents={academic:{label:'学术交流',title:'从一个研究问题开始。',body:'可以围绕文化内容的理解与生成、人机协作中的判断，或相关交互方法展开讨论。先了解双方正在关注的问题，再判断是否具有共同的研究切入点。',next:'可以从具体项目或方法出发，讨论相关性和可能的下一步。',prepare:['感兴趣的研究问题或项目','希望交流的方法、发现或疑问','可供阅读的相关工作（如有）']},culture:{label:'文化场景合作',title:'把真实场景带进研究。',body:'如果你的工作涉及文化图像、资料整理、专业判断或文化体验，可以围绕具体对象和人的工作讨论研究合作的可能性。',next:'先理解文化语境与专业工作，再共同判断什么问题值得研究、需要怎样的参与。这是讨论入口，不预先承诺具体服务。',prepare:['希望讨论的文化对象与使用场景','人在当前工作中遇到的问题','相关资料是否可以用于交流（如有）']},join:{label:'了解参与',title:'看看研究兴趣如何相遇。',body:'先从研究问题和已有项目了解团队，再围绕你的兴趣、方法经验或希望探索的题目，交流参与研究的可能性。',next:'导师个人主页提供招生、实习与访问说明。研究方向和学位专业不是同一件事，具体名额与资格请先阅读当年说明，再直接交流。',prepare:['感兴趣的研究问题','相关经历或作品（如有）','希望进一步了解的参与方式']}};
function contact(intent='academic'){if(!contactIntents[intent])intent='academic';const c=contactIntents[intent];return `<div class="shell">${heading('交流与合作','不同的背景，可以从共同关心的问题开始。','交流与合作')}<div class="contact-layout"><div class="contact-tabs" role="tablist" aria-label="交流意图">${Object.entries(contactIntents).map(([key,item])=>`<button id="contact-tab-${key}" role="tab" aria-selected="${key===intent}" aria-controls="contact-panel" tabindex="${key===intent?0:-1}" data-intent="${key}">${item.label}</button>`).join('')}</div><section class="contact-panel" id="contact-panel" role="tabpanel" aria-labelledby="contact-tab-${intent}"><h2>${c.title}</h2><p>${c.body}</p><h3>下一步如何展开</h3><p>${c.next}</p><h3>交流时可以带上</h3><ul>${c.prepare.map(item=>`<li>${item}</li>`).join('')}</ul><div class="contact-channel"><span class="label">导师公开学术邮箱</span><a class="contact-email" href="mailto:zejianlee@zju.edu.cn">zejianlee@zju.edu.cn ↗</a><small>李泽健 · 浙江大学<br>点击邮箱使用你的邮件应用联系。</small><a class="inline-link" href="${mentorHome}" target="_blank" rel="noopener">查看导师主页与参与说明 ↗</a></div>${inline(intent==='join'?'#/people':'#/research',intent==='join'?'先了解团队':'先阅读相关研究')}</section></div></div>`;}
const templates={questions:{name:'研究问题',purpose:'维护可以交叉关联项目的研究问题。不要用分类替代团队对正式研究方向的确认。',fields:[['问题名称','简短且容易理解的研究视角'],['具体问题','用一个真实问题解释其含义'],['研究说明','文化情境、人的活动与相关方法'],['关联项目','一个问题关联多个项目，允许交叉']]},outputs:{name:'论文与资源',purpose:'每项成果独立维护，再关联项目与贡献者。不同类型使用自己的字段。',fields:[['成果类型','论文 / 工具与系统 / 数据与资源'],['标题与摘要','清楚说明这是什么'],['题录或版本','作者、年份、发表场所，或工具/资源版本'],['访问链接','DOI、代码、演示、下载等实际可用入口'],['关联项目与成员','建立双向可导航的研究关系']]},members:{name:'团队成员',purpose:'老师逐条填写成员资料，项目页面引用这些信息，避免重复维护。',fields:[['姓名与角色','经团队确认的姓名和角色'],['研究兴趣','简短介绍关注的问题与方法'],['照片与替代文本','使用获准的照片，或保留无照片版式'],['个人链接','个人主页或获准公开的渠道'],['关联项目','参与的研究项目和成果']]},news:{name:'研究动态',purpose:'保存真实发生的进展，并让读者能回到完整项目。',fields:[['标题与摘要','一件具体发生的事'],['发生日期','与录入日期分开'],['正文与媒体','经过确认的文字与图片'],['关联内容','对应的项目、成果或成员']]},site:{name:'网站信息',purpose:'维护首页与关于页面的共同信息真源，保持联系和参与路径稳定。',fields:[['品牌名称','GAN lab'],['研究定位','AI、人机交互、传统文化及其关系'],['资源背景','三个已确认单位的资源关系'],['联系渠道','正式邮箱或团队确认的表单地址'],['首页精选','从已有项目与成果中选择，不另造一份内容']]}};
const input=(id,label,value,full=false,help='')=>`<div class="field ${full?'full':''}"><label for="${id}">${label}</label><input id="${id}" value="${esc(value)}" maxlength="250">${help?`<small>${help}</small>`:''}</div>`;
const area=(id,label,value,rows=4,help='')=>`<div class="field full"><label for="${id}">${label}</label><textarea id="${id}" rows="${rows}" maxlength="6000">${esc(value)}</textarea>${help?`<small>${help}</small>`:''}</div>`;
function editorFields(){if(editorTab==='basics')return `${input('edit-title','项目标题',draft.title,true,'草稿可以先保存标题，其他资料后续补充。')}${area('edit-summary','一句话研究介绍',draft.summary,3)}${input('edit-stage','当前阶段',draft.stage)}${input('edit-owner','成员显示说明',draft.owner)}<div class="field full"><fieldset><legend>关联研究视角（可多选）</legend><div class="checkboxes">${perspectives.map(p=>`<label><input type="checkbox" data-edit-perspective="${p.id}" ${draft.perspectives.includes(p.id)?'checked':''}>${p.title}</label>`).join('')}</div></fieldset><small>允许同一项目从多个视角被找到，不强制归入单一方向。</small></div>`;
if(editorTab==='narrative')return `${area('edit-problem','研究问题',draft.problem,3)}${area('edit-human','人的活动',draft.human,3)}${area('edit-ai','AI 的作用',draft.ai,3)}${area('edit-method','研究方法',draft.method,5,'每行一项方法或步骤，预览中按顺序展示。')}${area('edit-progress','当前进展',draft.progress,3)}`;
return `<div class="field full"><fieldset><legend>关联成果</legend><div class="checkboxes"><label><input type="checkbox" id="edit-output" ${draft.outputIds.includes('software')?'checked':''}>古画修复初版软件</label></div></fieldset><small>成果信息在“论文与资源”独立维护，项目只建立关联。</small></div><div class="field full"><label>关联成员</label><div class="soft-note" style="margin-top:0">已收录导师李泽健。具体项目的参与者仍需逐项确认；此试填样例不自动建立导师参与关系。</div></div><div class="field full"><label>项目媒体</label><div class="soft-note" style="margin-top:0">正式图片、图注、替代文本与使用范围在这里维护。此预览不上传真实媒体，也不把首页概念图当作项目成果。</div></div><div class="field full"><label>公开显示</label><div class="soft-note" style="margin-top:0">保存进入草稿，预览展示草稿；实际发布时才替换公开版本。资料不足时可保留草稿，网站的团队与联系入口仍然存在。</div></div>`;}
function admin(){const t=templates[adminType];return `<div class="shell admin-shell"><div class="admin-top"><div><h1>老师内容管理</h1><p>当前试填：古画软件样例。公开研究资料与这份样例分开。</p></div><a class="btn" href="#/">返回网站 ↗</a></div><div class="admin-layout"><nav class="admin-nav" aria-label="内容管理类型"><button data-admin="project" aria-current="${adminType==='project'?'page':'false'}">研究项目</button><button data-admin="questions" aria-current="${adminType==='questions'?'page':'false'}">研究问题</button><button data-admin="outputs" aria-current="${adminType==='outputs'?'page':'false'}">论文与资源</button><button data-admin="members" aria-current="${adminType==='members'?'page':'false'}">团队成员</button><button data-admin="news" aria-current="${adminType==='news'?'page':'false'}">研究动态</button><span>网站设置</span><button data-admin="site" aria-current="${adminType==='site'?'page':'false'}">网站信息</button></nav><section>${adminType==='project'?`<div class="editor-heading"><h2>编辑研究项目</h2><span class="status-badge" id="draft-status">${JSON.stringify(draft)===JSON.stringify(savedDraft)?'草稿':'有未保存修改'}</span></div><div class="editor-tabs" role="tablist" aria-label="项目编辑分段">${[['basics','基本信息'],['narrative','研究叙事'],['relations','关联与展示']].map(([id,label])=>`<button id="editor-tab-${id}" role="tab" aria-selected="${editorTab===id}" aria-controls="editor-panel" tabindex="${editorTab===id?0:-1}" data-editor-tab="${id}">${label}</button>`).join('')}</div><form id="project-editor"><div class="form-grid" id="editor-panel" role="tabpanel" aria-labelledby="editor-tab-${editorTab}">${editorFields()}</div><div class="editor-actions"><button class="btn primary" type="submit">保存草稿</button><button class="btn" type="button" id="preview-project">预览项目</button><button class="btn" disabled type="button" aria-describedby="editor-limit">发布内容</button></div><p class="editor-note" id="editor-limit">当前仅为内容管理演示。编辑内容只在本页面内存中保留，刷新后恢复。真实登录、保存、媒体上传和发布未接入。</p><p class="save-feedback" id="editor-feedback" role="status">${esc(toast)}</p></form>`:`<div class="template-title"><h2>${t.name}</h2><p>${t.purpose}</p></div><div class="template-fields">${t.fields.map(([label,value])=>`<div class="template-row"><strong>${label}</strong><span>${value}</span></div>`).join('')}</div><p class="editor-note">此页说明对应内容模板；本轮可实际试填研究项目，其他类型在正式后台阶段实现。</p><button class="btn" data-admin="project" style="margin-top:20px">返回项目编辑</button>`}</section></div></div>`;}
function getRoute(){const raw=location.hash.slice(1)||'/';const [path,query]=raw.split('?');return {path,params:new URLSearchParams(query)};}
function render({focus=true}={}){const {path,params}=getRoute();let html,title,nav='';previewing=false;
if(path==='/'){html=home();title='AI、人机交互与传统文化';}
else if(path==='/research'){html=research();title='研究';nav='research';}
else if(works.some(w=>path==='/research/'+w.id)){const w=works.find(w=>path==='/research/'+w.id);html=workDetail(w);title=w.name;nav='research';}
else if(path==='/outputs'){html=outputs();title='论文与研究资源';nav='outputs';}
else if(path==='/people'){html=people();title='团队';nav='people';}
else if(path==='/about'){html=about();title='关于';nav='about';}
else if(path==='/contact'){html=contact(params.get('intent')||'academic');title='交流与合作';}
else if(path==='/admin'){html=admin();title='老师内容管理';}
else if(path==='/preview'){html=projectDetail(draft,true);title='项目草稿预览';previewing=true;}
else{html=`<div class="shell">${heading('这个页面暂时不存在','可以从研究入口继续浏览。')}${inline('#/research','进入研究')}</div>`;title='页面未找到';}
$('main').innerHTML=html;document.title=`GAN lab · ${title}`;document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===nav)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(focus){window.scrollTo({top:0,behavior:'instant'});$('main').focus({preventScroll:true});}}
function collectForm(){const map={title:'edit-title',summary:'edit-summary',stage:'edit-stage',owner:'edit-owner',problem:'edit-problem',human:'edit-human',ai:'edit-ai',method:'edit-method',progress:'edit-progress'};for(const [key,id]of Object.entries(map)){if($(id))draft[key]=$(id).value;}if(document.querySelector('[data-edit-perspective]'))draft.perspectives=[...document.querySelectorAll('[data-edit-perspective]:checked')].map(e=>e.dataset.editPerspective);if($('edit-output'))draft.outputIds=$('edit-output').checked?['software']:[];}
function showDesign(){if(!$('design-dialog').open)$('design-dialog').showModal();}
$('open-design').addEventListener('click',showDesign);$('open-design-footer').addEventListener('click',showDesign);
document.addEventListener('click',e=>{if(e.target.closest('.skip')){e.preventDefault();$('main').focus();$('main').scrollIntoView();return;}const close=e.target.closest('[data-close]');if(close){$(close.dataset.close).close();return;}const p=e.target.closest('[data-perspective]');if(p){perspectiveIndex=Number(p.dataset.perspective);document.querySelectorAll('[data-perspective]').forEach(b=>{const selected=Number(b.dataset.perspective)===perspectiveIndex;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});$('perspective-panel').innerHTML=perspectivePanel(perspectiveIndex);$('perspective-panel').setAttribute('aria-labelledby',`perspective-tab-${perspectiveIndex}`);return;}const type=e.target.closest('[data-output-filter]');if(type){outputFilter=type.dataset.outputFilter;render({focus:false});document.querySelector(`[data-output-filter="${outputFilter}"]`).focus({preventScroll:true});return;}const intent=e.target.closest('[data-intent]');if(intent){history.replaceState(null,'',`#/contact?intent=${intent.dataset.intent}`);render({focus:false});document.querySelector(`[data-intent="${intent.dataset.intent}"]`).focus({preventScroll:true});return;}const adminBtn=e.target.closest('[data-admin],[data-admin-type]');if(adminBtn){collectForm();adminType=adminBtn.dataset.admin||adminBtn.dataset.adminType;toast='';if(getRoute().path==='/admin')render({focus:false});else location.hash='/admin';return;}const tab=e.target.closest('[data-editor-tab]');if(tab){collectForm();editorTab=tab.dataset.editorTab;toast='';render({focus:false});document.querySelector(`[data-editor-tab="${editorTab}"]`).focus({preventScroll:true});return;}if(e.target.closest('#preview-project')){collectForm();location.hash='/preview';return;}if(e.target.closest('[data-return-editor]')){location.hash='/admin';return;}const section=e.target.closest('[data-section]');if(section){e.preventDefault();$(section.dataset.section)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});return;}});
document.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key))return;const tab=e.target.closest('[role=tab]');if(!tab)return;const list=tab.closest('[role=tablist]'),tabs=[...list.querySelectorAll('[role=tab]')];let idx=tabs.indexOf(tab);if(e.key==='Home')idx=0;else if(e.key==='End')idx=tabs.length-1;else idx=(idx+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+tabs.length)%tabs.length;e.preventDefault();const target=tabs[idx],id=target.id;target.click();$(id)?.focus({preventScroll:true});});
document.addEventListener('input',e=>{if(!e.target.closest('#project-editor'))return;collectForm();if($('draft-status'))$('draft-status').textContent='有未保存修改';if($('editor-feedback'))$('editor-feedback').textContent='';});
document.addEventListener('submit',e=>{if(e.target.id!=='project-editor')return;e.preventDefault();collectForm();if(!draft.title.trim()){editorTab='basics';toast='请先填写项目标题，其他资料可以稍后补充。';render({focus:false});$('edit-title').focus();return;}savedDraft=structuredClone(draft);toast='草稿已保留在当前页面。预览可以查看修改，访客内容保持原版本。';$('draft-status').textContent='草稿已保存';$('editor-feedback').textContent=toast;});
window.addEventListener('hashchange',()=>render());render({focus:false});
